/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.majorproject;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Sagar prasad
 */
public class f3 extends javax.swing.JFrame {

    /**
     * Creates new form f3
     */
    public f3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel1.setText("Fill Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(365, 6, 129, 37);

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel2.setText("Venue:-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(28, 46, 70, 25);

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel3.setText("Caterers:-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(28, 118, 80, 25);

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel4.setText("Photographers:-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(28, 246, 120, 25);

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel5.setText("Make-Up Artist");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(28, 342, 120, 25);

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel6.setText("No of Guest:-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(381, 46, 110, 25);

        jLabel7.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel7.setText("Types of Food:-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(381, 138, 120, 25);

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel8.setText("Decorators:-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(28, 412, 90, 25);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(153, 45, 156, 22);

        jCheckBox1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jCheckBox1.setText("Sai Caterers");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(153, 120, 97, 23);

        jCheckBox2.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jCheckBox2.setText("Annapurna Caterers");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(153, 149, 129, 23);

        jCheckBox3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        jCheckBox3.setText("Kitchen Caterers");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(153, 178, 118, 23);

        jRadioButton1.setText("Yes");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(154, 246, 41, 21);

        jRadioButton2.setText("No");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(154, 277, 39, 21);

        jRadioButton3.setText("Yes");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(146, 342, 41, 21);

        jRadioButton4.setText("No");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(146, 373, 39, 21);

        jCheckBox4.setText("3 Star");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(146, 412, 85, 20);

        jCheckBox5.setText("4 Star");
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(146, 443, 85, 20);

        jCheckBox6.setText("5 star");
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(146, 469, 85, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(512, 45, 139, 22);

        jCheckBox7.setText("Veg");
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(512, 138, 85, 20);

        jCheckBox8.setText("Non-Veg");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(512, 169, 85, 20);

        jCheckBox9.setText("North Indian");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox9);
        jCheckBox9.setBounds(512, 195, 91, 20);

        jCheckBox10.setText("Chinese");
        jPanel1.add(jCheckBox10);
        jCheckBox10.setBounds(512, 227, 91, 20);

        jCheckBox11.setText("South Indian");
        jPanel1.add(jCheckBox11);
        jCheckBox11.setBounds(512, 259, 91, 20);

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel9.setText("Additional:-");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(381, 277, 100, 25);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(405, 329, 234, 86);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(640, 459, 100, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wedding1.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 900, 500);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(750, 450, 130, 40);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        try {
            String Venue=jTextField1.getText();
            String Guest=jTextField2.getText();
            String Additional=jTextArea1.getText();
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/majorproject","root","");
            PreparedStatement Ps=con.prepareStatement("insert into data(Venue,Guest,Additional,Caterers,Photographer,MakeupArtist,Decorators,Food)values(?,?,?,?,?,?,?,?)");
            Ps.setString(1,Venue);
            Ps.setString(2,Guest);
            Ps.setString(3,Additional);
            if(jCheckBox1.isSelected()){
                Ps.setString(4,jCheckBox1.getText());
                if(jCheckBox2.isSelected()){
                 Ps.setString(4,jCheckBox2.getText());
                }
            }else
                Ps.setString(4,jCheckBox3.getText());
            if(jRadioButton1.isSelected()){
              Ps.setString(5,jRadioButton1.getText());  
            }else
               Ps.setString(5,jRadioButton2.getText());
            
            if(jRadioButton3.isSelected()){
                Ps.setString(6,jRadioButton3.getText());
            }else
                Ps.setString(6,jRadioButton4.getText());
            
            if(jCheckBox4.isSelected()){
               Ps.setString(7,jCheckBox4.getText());
               if(jCheckBox5.isSelected()){
                 Ps.setString(7,jCheckBox5.getText());  
               }
            }else
              Ps.setString(7,jCheckBox6.getText());
            
            if(jCheckBox7.isSelected()){
                Ps.setString(8,jCheckBox7.getText());
                if(jCheckBox8.isSelected()){
                    Ps.setString(8,jCheckBox8.getText());
                    if(jCheckBox9.isSelected()){
                       Ps.setString(8,jCheckBox9.getText());
                       if(jCheckBox10.isSelected()){
                           Ps.setString(8,jCheckBox10.getText());
                        
                           
                       }
                    }
                }
            }else
                Ps.setString(8,jCheckBox11.getText());
            
            Ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Submitted Successfully");
        } catch (HeadlessException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Services().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new f3().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private static class JOptionpane {


        public JOptionpane() {
        }
    }
}
